export const INesMappers = [
  { "mapper": "Mapper0", "designations": ["NROM"], "status": "Available" },
  { "mapper": "Mapper1", "designations": ["SxROM", "MMC1"], "status": "Not implemented" },
  { "mapper": "Mapper2", "designations": ["UxROM"], "status": "Available" },
  { "mapper": "Mapper3", "designations": ["CNROM"], "status": "Available" },
  { "mapper": "Mapper4", "designations": ["TxROM", "MMC3", "MMC6"], "status": "Not implemented" },
  { "mapper": "Mapper5", "designations": ["ExROM", "MMC5"], "status": "Not implemented" },
  { "mapper": "Mapper7", "designations": ["AxROM"], "status": "Available" },
  { "mapper": "Mapper9", "designations": ["PxROM", "MMC2"], "status": "Not implemented" },
  { "mapper": "Mapper10", "designations": ["FxROM", "MMC4"], "status": "Not implemented" },
  { "mapper": "Mapper11", "designations": ["Color Dreams"], "status": "Not implemented" },
  { "mapper": "Mapper13", "designations": ["CPROM"], "status": "Not implemented" },
  { "mapper": "Mapper15", "designations": ["100-in-1 Contra Function 16"], "status": "Not implemented" },
  { "mapper": "Mapper16", "designations": ["Bandai EPROM (24C02)"], "status": "Not implemented" },
  { "mapper": "Mapper18", "designations": ["Jaleco SS8806"], "status": "Not implemented" },
  { "mapper": "Mapper19", "designations": ["Namco 163"], "status": "Not implemented" },
  { "mapper": "Mapper21", "designations": ["VRC4a", "VRC4c"], "status": "Not implemented" },
  { "mapper": "Mapper22", "designations": ["VRC2a"], "status": "Not implemented" },
  { "mapper": "Mapper23", "designations": ["VRC2b", "VRC4e"], "status": "Not implemented" },
  { "mapper": "Mapper24", "designations": ["VRC6a"], "status": "Not implemented" },
  { "mapper": "Mapper25", "designations": ["VRC4b", "VRC4d"], "status": "Not implemented" },
  { "mapper": "Mapper26", "designations": ["VRC6b"], "status": "Not implemented" },
  { "mapper": "Mapper34", "designations": ["BNROM", "NINA-001"], "status": "Not implemented" },
  { "mapper": "Mapper64", "designations": ["RAMBO-1"], "status": "Not implemented" },
  { "mapper": "Mapper66", "designations": ["GxROM", "MxROM"], "status": "Not implemented" },
  { "mapper": "Mapper68", "designations": ["After Burner"], "status": "Not implemented" },
  { "mapper": "Mapper69", "designations": ["FME-7", "Sunsoft 5B"], "status": "Not implemented" },
  { "mapper": "Mapper71", "designations": ["Camerica/Codemasters"], "status": "Not implemented" },
  { "mapper": "Mapper73", "designations": ["VRC3"], "status": "Not implemented" },
  { "mapper": "Mapper74", "designations": ["Pirate MMC3 derivative"], "status": "Not implemented" },
  { "mapper": "Mapper75", "designations": ["VRC1"], "status": "Not implemented" },
  { "mapper": "Mapper76", "designations": ["Namco 109 variant"], "status": "Not implemented" },
  { "mapper": "Mapper79", "designations": ["NINA-03", "NINA-06"], "status": "Not implemented" },
  { "mapper": "Mapper85", "designations": ["VRC7"], "status": "Not implemented" },
  { "mapper": "Mapper86", "designations": ["JALECO-JF-13"], "status": "Not implemented" },
  { "mapper": "Mapper94", "designations": ["Senjou no Ookami"], "status": "Not implemented" },
  { "mapper": "Mapper105", "designations": ["NES-EVENT"], "status": "Not implemented" },
  { "mapper": "Mapper113", "designations": ["NINA-03/NINA-06??"], "status": "Not implemented" },
  { "mapper": "Mapper118", "designations": ["TxSROM", "MMC3"], "status": "Not implemented" },
  { "mapper": "Mapper119", "designations": ["TQROM", "MMC3"], "status": "Not implemented" },
  { "mapper": "Mapper159", "designations": ["Bandai EPROM (24C01)"], "status": "Not implemented" },
  { "mapper": "Mapper166", "designations": ["SUBOR"], "status": "Not implemented" },
  { "mapper": "Mapper167", "designations": ["SUBOR"], "status": "Not implemented" },
  { "mapper": "Mapper180", "designations": ["Crazy Climber"], "status": "Not implemented" },
  { "mapper": "Mapper185", "designations": ["CNROM with protection diodes"], "status": "Not implemented" },
  { "mapper": "Mapper192", "designations": ["Pirate MMC3 derivative"], "status": "Not implemented" },
  { "mapper": "Mapper206", "designations": ["DxROM", "Namco 118", "MIMIC-1"], "status": "Not implemented" },
  { "mapper": "Mapper210", "designations": ["Namco 175", "Namco 340"], "status": "Not implemented" },
  { "mapper": "Mapper228", "designations": ["Action 52"], "status": "Not implemented" },
  { "mapper": "Mapper232", "designations": ["Camerica/Codemasters Quattro"], "status": "Not implemented" }
];
